# Generated by Django 3.2.12 on 2022-03-23 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keycap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(choices=[('DSA', 'DSA'), ('SA', 'DSA'), ('cherry', 'Cherry'), ('XDA', 'XDA')], default='DSA', max_length=6)),
                ('material', models.CharField(choices=[('abs', 'ABS'), ('ptb', 'ABS'), ('gmk', 'GMK')], default='abs', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('switches', models.CharField(choices=[('red', 'Red'), ('black', 'Black'), ('brown', 'Brown'), ('blue', 'Blue')], default='red', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keycap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.keycap')),
            ],
        ),
    ]
